apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-config
  namespace: fraud-detection
data:
  MLFLOW_TRACKING_URI: "file:/app/mlruns"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "fraud"
  POSTGRES_PASSWORD: "changeme"
  POSTGRES_DB: "fraud"
  FEAST_REPO_PATH: "/app/features"
